apiVersion: v1
kind: Service
metadata:
  name: servicea-service
spec:
  type: ClusterIP #{{ .Values.service.type }}
  # Kubernetes load balancer is not required as we are using istio gateway
  selector:
    app: servicea
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
      # nodePort: {{ .Values.service.nodePort }}
    