replicaCount: 1
image:
  repository: gcr.io/flawless-mason-258102
  tag: 2.0.0
  pullPolicy: Always
labels:
  app: serviceb
  ns: microservices
service:
  type: ClusterIP
  internalPort: 8081
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi