replicaCount: 1
imagePullSecrets:
image:
  repository: asia.gcr.io/flawless-mason-258102/serviceb:1.0.0
  tag: dev
  pullPolicy: Always
labels:
  app: serviceb
service:
  type: clusterIP
  externalPort: 80
  internalPort: 8081
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi