replicaCount: 1
imagePullSecrets:
image:
  repository: gcr.io/qwiklabs-gcp-00-fc09b4cc0edd/serviceb:1.0.0
  tag: dev
  pullPolicy: Always
labels:
  app: serviceb
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8081
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi