apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: servicea-deployment
  labels:
    app: servicea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicea
  template:
    metadata:
      labels:
        app: servicea
    spec:
      containers:
        - name: servicea
          image: gcr.io/flawless-mason-258102/servicea:1.0.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
                path: /welcome
                port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
#          resources:
#{{ toYaml .Values.resources | indent 12 }}