apiVersion: v1
kind: Deployment
metadata:
  name: "{{ .Values.labels.app }}-deployment"
  labels:
    app: "{{ .Values.labels.app }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.labels.app }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.labels.app }}"
    spec:
      containers:
        - name: "{{ .Values.labels.app }}"
          image: "{{ .Values.image.repository }}"
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
                path: /welcome
                port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 30
            periodSeconds: 20
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
{{ toYaml .Values.resources | indent 12 }}