apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.labels.app }}-service
spec:
  type: ClusterIP #{{ .Values.service.type }}
  # Kubernetes load balancer is not required as we are using istio gateway
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      # nodePort: {{ .Values.service.nodePort }}
    