apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: serviceb-deployment
  labels:
    app: serviceb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceb
  template:
    metadata:
      labels:
        app: serviceb
    spec:
      containers:
        - name: serviceb
          image: gcr.io/flawless-mason-258102/serviceb:1.0.0
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
                path: /welcome
                port: 8081
            initialDelaySeconds: 30
            periodSeconds: 20
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 20