apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.labels.app }}-deployment
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.labels.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
        - name: {{ .Values.labels.app }}
          image: "{{ .Values.image.repository }}/{{ .Values.labels.app }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
                path: /welcome
                port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 30
            periodSeconds: 20
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 30
            periodSeconds: 20